---
title: "Basic laws and equations"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Ideal gas law

Using the universal gas constant:

$$
p V = n R^* T
$$

where

$n$ = number of moles,

$R*$ = ideal (universal gas constant) = $8.3$ $J\ mol^{-1}\ K^{-1}$

An increase in temperature leads to an increase in pressure, or volume, or both.

With the specific gas constant:

$$
p V = n M R T = m R T
$$

where

$M$ = molar mass (weight of 1 mole), with unit $kg/mol$

$R$ = $R^*/M$, with unit $Jkg^{-1}K^{-1}$

$m$ = mass

Or, with the specific volume $v = \frac{V}{m}$ :

$$
p v = R T
$$

Or, because $\frac{n \ M}{V} = \frac{1}{v} = \rho$ :

$$
p = \rho R T
$$

## Hydrostatic equation

In hydrostatic balance, the gravitational force acting on a parcel with horizontal area A and vertical extension z, $g \rho A dz$, and the pressure gradient force, $-A dp$, cancel each other:

$$
g \rho A dz = -A dp
$$ This yields the hydrostatic equation:

$$
-\frac{dp}{dz} = p(z + dz) - p(z) = g \rho
$$ Or with partial derivatives:

$$
\frac{\partial p}{\partial z} = -g \rho
$$ This yields the definition of hydrostatic pressure:

$$
p(z) = \int_z^\infty \rho g dz 
$$

## Hypsometric equation

Under hydrostatic balance, pressure is

$$
ln(\frac{p_2}{p_1}) = -\int_{z1}^{z2} F(z) dz
$$

or

$$
p_2 = p_1 \ e^{-\int_{z1}^{z2} F(z) dz}
$$

where $F = \frac{g}{TR}$. (For a given location and time, $F$ varies only with $z$.)

Thus, pressure decays exponentially with height in the atmosphere.

Solving for height yields the hyposometric equation. Under the hydrostatic assumption, we have

$$
z_2 = z_1 + \frac{2 R_1 R_2 T_1 T_2}{g_1 R_2 T_2 + g_2R_1T_1} ln\frac{p_1}{p_2}
$$

where

$g_i$ is the gravitational constant,

$R_i$ is the gas constant, and

$T_i$ is the temperature at elevation $z_i$.

Under the assumption that $g$ and $R$ are constant, we have

$$
z_2 = z_1 + \frac{2 R T_1 T_2}{g (T_1 + T_2)} ln\frac{p_1}{p_2}
$$

Further simplifying to use one average temperature $T = \frac{T_1 + T_2}{2}$ for a layer, we have

$$
z_2 = z_1 + \frac{RT}{g} ln\frac{p_1}{p_2}
$$
