---
title: "Internal energy, enthalpy and entropy"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Internal energy

The first law of thermodynamics says that energy is conserved:

$$
dU = q_{in} - pdV = q_{in} - W_{by} = 0
$$

Here $q_{in}$ is heat put *into* the system (positive), while $pdV$ is work done *by* the system (positive).

To see why work done by a system is $pdV$: If a gas expands against applied pressure, we have

$$
\Delta W = Fdx = pA\ dx = pdV
$$

So if the energy of a gas that is heated stays the same, it must also have lost energy through expansion.

Or if is cooled but energy is constant, it must also have been compressed.

If there is no change in volume, $dU$ is equal to just the amount of heat put in, $q_{in}$.

Put differently, at constant volume,

$$
dU= U_2 - U_1 = \int_{T_1}^{T_2} c_v(T) dT
$$

where $c_v$ is specific heat capacity at *constant volume*.

The internal energy $U$ then is

$$
U = m c_v T
$$

## Enthalpy

If volume is not constant, the expression for $dU$ does not simplify. If volume is not constant, but pressure is, we therefore work with a different state function: enthalpy.

Enthalpy is defined as internal energy plus potential energy

$$
H = U + pV
$$

The change in enthalpy $dH$ is

$$
\begin{align}
dH &= dU + d(pV)\\
&= dU + pdV + Vdp
\end{align}
$$

But at constant pressure, this is

$$
\begin{align}
dH &= dU + pdV 
\end{align}
$$

Which means that

$$
dH = q_{in}
$$

Put differently, at constant pressure,$$
dH = H_2 - H_1 = \int_{T_1}^{T_2} c_p(T) dT
$$

where $c_p$ is specific heat capacity at *constant pressure*. Put differently,

$$
H = m c_p T
$$

The constant pressure process is more efficient at heat absorption, so

$$
c_p \ge c_v
$$

The difference between both is the specific gas constant:

$$
R = c_p - c_v
$$

If pressure is not constant, the differential of enthalpy subsumes changes in internal energy as well as work done on a system:

$$
dH = dU + pdV + Vdp
$$

or

$$
dH = dQ + Vdp
$$

## Potential energy

The change in potential energy is

$$
dE_p = g \ z \ dm = g\ z\ \rho\ dV = g\ z\ \rho\ F\ dz
$$

## Relationship of potential and internal energy

$$
E_p = \frac{R}{c_v} \ E_i
$$

## Total potential energy

Together, potential and internal energy make up the total potential energy. That is the same as *enthalpy*:

$$
E_{total} = E_p + U = \eta U = H
$$

where $\eta = \frac{c_p}{c_v}$
